# Generated by Django 4.2.7 on 2025-12-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.CharField(blank=True, help_text='Например: глютен, лактоза', max_length=200, verbose_name='Аллергены'),
        ),
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.IntegerField(blank=True, null=True, verbose_name='Калории (ккал)'),
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, help_text='Список ингредиентов', verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='product',
            name='cooking_time',
            field=models.CharField(blank=True, help_text='Например: 15-20 мин', max_length=50, verbose_name='Время приготовления'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutritional_info',
            field=models.TextField(blank=True, help_text='Белки, жиры, углеводы', verbose_name='Пищевая ценность'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, help_text='Например: 250г, 500мл', max_length=50, verbose_name='Вес/Объем'),
        ),
    ]
