# Generated by Django 4.2.7 on 2025-12-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_product_allergens_product_calories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Логотип')),
                ('site_name', models.CharField(default='QR Hotel Service', max_length=100, verbose_name='Название сайта')),
                ('telegram_bot_token', models.CharField(blank=True, help_text='Токен бота от @BotFather', max_length=200, verbose_name='Telegram Bot Token')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='ID группы или канала для уведомлений', max_length=100, verbose_name='Telegram Chat ID')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
