# Generated by Django 4.2.7 on 2025-12-17 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='hotel.building', verbose_name='Корпус'),
        ),
    ]
