# Generated by Django 4.2.7 on 2025-12-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_floor_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_viewed',
            field=models.BooleanField(default=False, verbose_name='Просмотрен в дашборде'),
        ),
    ]
