# Generated by Django 4.2.7 on 2025-12-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_order_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notification_sound',
            field=models.FileField(blank=True, help_text='Загрузите свой звук уведомления (MP3, WAV, OGG). Если не загружен, будет использован звук по умолчанию.', null=True, upload_to='settings/sounds/', verbose_name='Звук уведомления'),
        ),
    ]
