# Generated by Django 4.2.7 on 2025-12-26 05:03

from django.db import migrations, models
import uuid


def generate_tokens_for_buildings(apps, schema_editor):
    """Генерирует токены для существующих корпусов"""
    Building = apps.get_model('hotel', 'Building')
    for building in Building.objects.filter(token__isnull=True):
        building.token = uuid.uuid4()
        building.save(update_fields=['token'])


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_sitesettings_notification_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='building',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR-код'),
        ),
        migrations.AddField(
            model_name='building',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL-адрес'),
        ),
        migrations.AddField(
            model_name='building',
            name='token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='Токен'),
        ),
        migrations.RunPython(generate_tokens_for_buildings, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='building',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен'),
        ),
    ]
