# Generated by Django 4.2.7 on 2025-12-26 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_add_building_qr_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hotel.building', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hotel.room', verbose_name='Номер'),
        ),
    ]
