# Generated by Django 4.2.7 on 2025-12-26 05:26

from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.utils.text import slugify


def populate_floor_name_and_slug(apps, schema_editor):
    """Заполняет name и slug для существующих этажей"""
    Floor = apps.get_model('hotel', 'Floor')
    for floor in Floor.objects.all():
        # Если name пустое, заполняем из number
        if not floor.name:
            if floor.number is not None:
                floor.name = f"Этаж {floor.number}"
            else:
                floor.name = "Этаж"
        
        # Генерируем slug из name
        if not floor.slug:
            transliterated = slugify(floor.name, allow_unicode=False)
            if not transliterated:
                transliterated = f"floor-{floor.id}"
            
            # Убеждаемся, что slug уникален
            original_slug = transliterated
            counter = 1
            while Floor.objects.filter(slug=transliterated).exclude(pk=floor.pk).exists():
                transliterated = f"{original_slug}-{counter}"
                counter += 1
            
            floor.slug = transliterated
            floor.save(update_fields=['name', 'slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_add_building_to_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='floor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='floor',
            name='name',
            field=models.CharField(default='', help_text='Например: Цоколь, 1 этаж, 2 этаж', max_length=100, verbose_name='Название этажа'),
        ),
        migrations.AddField(
            model_name='floor',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR-код'),
        ),
        migrations.AddField(
            model_name='floor',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL-адрес'),
        ),
        migrations.AddField(
            model_name='floor',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен'),
        ),
        migrations.AddField(
            model_name='order',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hotel.floor', verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='number',
            field=models.IntegerField(blank=True, help_text='Используется для сортировки, может быть пустым', null=True, verbose_name='Номер этажа (для сортировки)'),
        ),
        migrations.RunPython(populate_floor_name_and_slug, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('building', 'slug')},
        ),
    ]
